const HOUSE_EDGE = 0.04;
const MINES_TILE_COUNT = 25;
const state = loadState();
const session = { plays: 0, wagered: 0 };
let minesRound = null;
let blackjackRound = null;
let busy = false;

function $(id) { return document.getElementById(id); }
function on(id, event, fn) { const el = $(id); if (el) el.addEventListener(event, fn); }
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
function loadState() { const saved = localStorage.getItem('donutVaultState'); return saved ? JSON.parse(saved) : { balance: 0, xp: 0, level: 1, lastBonus: null, logs: ['Wallet created. Deposit DonutSMP cash to start playing.'] }; }
function saveState() { localStorage.setItem('donutVaultState', JSON.stringify(state)); }
function money(n) { return '$' + Math.floor(Number(n || 0)).toLocaleString(); }
function randInt(max) { return Math.floor(Math.random() * max); }
function clamp(n, min, max) { return Math.max(min, Math.min(max, n)); }
function payoutMultiplier(trueOdds) { return Math.max(1.01, (1 / trueOdds) * (1 - HOUSE_EDGE)); }
function getBet(id) { return Math.floor(Number($(id)?.value)); }
function toast(message) { const el = $('toast'); if (!el) return; el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2500); }
function setStatus(id, text, type = '') { const el = $(id); if (!el) return; el.className = 'mini-status ' + type; el.innerHTML = text; }
function lock(ms = 900) { busy = true; setTimeout(() => busy = false, ms); }

function addXp(amount) { state.xp += amount; while (state.xp >= 100) { state.xp -= 100; state.level += 1; toast('Level up! You reached level ' + state.level + '.'); } }
function addLog(text) { state.logs.unshift(text); state.logs = state.logs.slice(0, 8); saveState(); render(); }
function render() {
  document.querySelectorAll('#balanceDisplay, .js-balance').forEach(el => el.textContent = money(state.balance));
  if ($('levelDisplay')) $('levelDisplay').textContent = state.level;
  if ($('xpDisplay')) $('xpDisplay').textContent = state.xp + ' / 100';
  if ($('activityLog')) $('activityLog').innerHTML = state.logs.map(log => `<div class="log-item">${log}</div>`).join('');
  if ($('sessionStats')) $('sessionStats').textContent = `${session.plays} plays · ${money(session.wagered)} wagered`;
}
function chargeBet(amount) { if (busy) return 'Wait for the animation to finish.'; if (!amount || amount <= 0) return 'Enter a valid bet.'; if (amount > state.balance) return 'Not enough arcade balance.'; state.balance -= amount; session.plays++; session.wagered += amount; addXp(Math.min(12, Math.ceil(amount / 1000))); saveState(); render(); return null; }
function pay(amount, label) { const win = Math.floor(amount); state.balance += win; addXp(Math.min(20, Math.ceil(win / 1500))); if (label) addLog(`<b>${label}:</b> won ${money(win)}.`); saveState(); render(); return win; }
function deposit() { const user = $('depositUser')?.value.trim(); const amount = Math.floor(Number($('depositAmount')?.value)); if (!user) return toast('Enter your Minecraft username first.'); if (!amount || amount <= 0) return toast('Enter a valid deposit amount.'); state.balance += amount; addXp(Math.min(40, Math.ceil(amount / 1000))); addLog(`<b>Deposit credited:</b> ${money(amount)} from ${user}.`); if ($('depositAmount')) $('depositAmount').value = ''; toast('Deposit credited.'); }
function withdraw() { const user = $('withdrawUser')?.value.trim(); const amount = Math.floor(Number($('withdrawAmount')?.value)); if (!user) return toast('Enter your Minecraft username first.'); if (!amount || amount <= 0) return toast('Enter a valid withdrawal amount.'); if (amount > state.balance) return toast('Not enough arcade balance.'); state.balance -= amount; addLog(`<b>Payout instruction:</b> /pay ${user} ${amount.toLocaleString()} DonutSMP cash.`); if ($('withdrawAmount')) $('withdrawAmount').value = ''; toast('Withdrawal created.'); }
function dailyBonus() { const today = new Date().toDateString(); if (state.lastBonus === today) return toast('Daily bonus already claimed today.'); state.lastBonus = today; state.balance += 500; addXp(15); addLog('<b>Daily bonus:</b> $500 claimed.'); }
function switchTab(target) { document.querySelectorAll('.tab').forEach(btn => btn.classList.toggle('active', btn.dataset.target === target)); document.querySelectorAll('.game-stage').forEach(stage => stage.classList.toggle('active', stage.id === target)); history.replaceState(null, '', '#' + target); }
function openHashGame() { const id = location.hash.slice(1); if (id && $(id)) switchTab(id); }

function renderMines(revealAll = false) { const board = $('minesBoard'); if (!board) return; board.innerHTML = ''; for (let i = 0; i < MINES_TILE_COUNT; i++) { const btn = document.createElement('button'); btn.className = 'tile'; const revealed = minesRound?.revealed.includes(i); const isMine = minesRound?.mines.includes(i); if (revealed) { btn.textContent = '◆'; btn.classList.add('safe'); } else if ((revealAll || minesRound?.ended) && isMine) { btn.textContent = '💣'; btn.classList.add('mine'); } else { btn.textContent = '?'; } btn.disabled = !minesRound || minesRound.ended || revealed || busy; btn.addEventListener('click', () => pickMineTile(i)); board.appendChild(btn); } }
function startMines() { const bet = getBet('minesBet'); const mineCount = Number($('minesCount')?.value || 3); const err = chargeBet(bet); if (err) return toast(err); const mines = new Set(); while (mines.size < mineCount) mines.add(randInt(MINES_TILE_COUNT)); minesRound = { bet, mineCount, mines: [...mines], revealed: [], ended: false }; setStatus('minesStatus', `Round started. The 5x5 field is live. ${mineCount} bombs hidden.`); renderMines(); }
function minesMult() { if (!minesRound || !minesRound.revealed.length) return 1; const safeTotal = MINES_TILE_COUNT - minesRound.mineCount; let odds = 1; for (let i = 0; i < minesRound.revealed.length; i++) odds *= (safeTotal - i) / (MINES_TILE_COUNT - i); return payoutMultiplier(odds); }
async function pickMineTile(i) { if (!minesRound || minesRound.ended || busy) return; busy = true; const tiles = document.querySelectorAll('.tile'); tiles[i]?.classList.add('scanning'); setStatus('minesStatus', 'Scanning tile...'); await sleep(520); if (minesRound.mines.includes(i)) { minesRound.ended = true; addLog(`<b>Mines:</b> hit a bomb and lost ${money(minesRound.bet)}.`); setStatus('minesStatus', `💣 Bomb hit. Lost ${money(minesRound.bet)}.`, 'lose'); busy = false; renderMines(true); } else { minesRound.revealed.push(i); const mult = minesMult(); setStatus('minesStatus', `◆ Diamond found. ${mult.toFixed(2)}x · Cashout ${money(minesRound.bet * mult)}. Keep picking diamonds or cash out.`, 'win'); busy = false; renderMines(); } }
async function cashoutMines() { if (!minesRound || minesRound.ended || !minesRound.revealed.length) return toast('Reveal at least one diamond first.'); if (busy) return; busy = true; setStatus('minesStatus', 'Locking cashout... revealing bombs.'); await sleep(650); const won = pay(minesRound.bet * minesMult(), 'Mines cashout'); minesRound.ended = true; renderMines(true); setStatus('minesStatus', `◆ Cashed out for ${money(won)}. Bombs revealed.`, 'win'); busy = false; }

function card() { const ranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']; const suits = ['♠','♥','♦','♣']; return { rank: ranks[randInt(13)], suit: suits[randInt(4)] }; }
function handValue(hand) { let total = 0, aces = 0; hand.forEach(c => { if (c.rank === 'A') { total += 11; aces++; } else if (['J','Q','K'].includes(c.rank)) total += 10; else total += Number(c.rank); }); while (total > 21 && aces) { total -= 10; aces--; } return total; }
function cardMarkup(c, hidden = false) { return `<div class="card dealt ${hidden ? 'back' : (['♥','♦'].includes(c.suit) ? 'red' : '')}">${hidden ? '' : c.rank + '<small>' + c.suit + '</small>'}</div>`; }
function renderCards(id, hand, hideFirst = false, stagger = false) { const el = $(id); if (!el) return; el.innerHTML = hand.map((c, i) => cardMarkup(c, hideFirst && i === 0)).join(''); if (stagger) el.querySelectorAll('.card').forEach((cardEl, i) => cardEl.style.animationDelay = `${i * 170}ms`); }
function renderBlackjack(hide = false, stagger = false) { if (!blackjackRound) return; renderCards('dealerCards', blackjackRound.dealer, hide, stagger); renderCards('playerCards', blackjackRound.player, false, stagger); if ($('playerScore')) $('playerScore').textContent = '(' + handValue(blackjackRound.player) + ')'; if ($('dealerScore')) $('dealerScore').textContent = hide ? '' : '(' + handValue(blackjackRound.dealer) + ')'; }
async function dealBlackjack() { const bet = getBet('blackjackBet'); const err = chargeBet(bet); if (err) return toast(err); busy = true; blackjackRound = { bet, player: [], dealer: [], over: false }; setStatus('blackjackStatus', 'Shuffling deck...'); await sleep(450); for (let i = 0; i < 2; i++) { blackjackRound.player.push(card()); renderBlackjack(true, true); await sleep(360); blackjackRound.dealer.push(card()); renderBlackjack(true, true); await sleep(360); } setStatus('blackjackStatus', 'Cards dealt. Hit or stand.', 'win'); busy = false; }
async function hitBlackjack() { if (!blackjackRound || blackjackRound.over) return toast('Deal first.'); if (busy) return; busy = true; setStatus('blackjackStatus', 'Dealing your hit...'); await sleep(420); blackjackRound.player.push(card()); const v = handValue(blackjackRound.player); renderBlackjack(true, true); if (v > 21) { blackjackRound.over = true; await sleep(400); addLog(`<b>Blackjack:</b> busted and lost ${money(blackjackRound.bet)}.`); setStatus('blackjackStatus', 'Bust. Dealer wins.', 'lose'); renderBlackjack(false, true); } busy = false; }
async function standBlackjack() { if (!blackjackRound || blackjackRound.over) return toast('Deal first.'); if (busy) return; busy = true; setStatus('blackjackStatus', 'Dealer reveals...'); renderBlackjack(false, true); await sleep(600); while (handValue(blackjackRound.dealer) < 17) { blackjackRound.dealer.push(card()); renderBlackjack(false, true); await sleep(520); } const p = handValue(blackjackRound.player), d = handValue(blackjackRound.dealer); blackjackRound.over = true; if (d > 21 || p > d) { const won = pay(blackjackRound.bet * 1.92, 'Blackjack'); setStatus('blackjackStatus', `You beat the dealer. Won ${money(won)}.`, 'win'); } else if (p === d) { state.balance += blackjackRound.bet; addLog('<b>Blackjack:</b> push, bet returned.'); render(); setStatus('blackjackStatus', 'Push. Bet returned.'); } else { addLog(`<b>Blackjack:</b> dealer won, lost ${money(blackjackRound.bet)}.`); setStatus('blackjackStatus', 'Dealer wins.', 'lose'); } busy = false; }

async function flipCoin(choice) { const bet = getBet('coinBet'); const err = chargeBet(bet); if (err) return toast(err); busy = true; const display = $('coinDisplay'); display?.classList.add('flipping'); if (display) display.textContent = ''; setStatus('coinStatus', 'Coin spinning...'); await sleep(1000); const result = Math.random() < 0.5 ? 'Heads' : 'Tails'; display?.classList.remove('flipping'); if (display) display.textContent = result === 'Heads' ? 'H' : 'T'; if (choice === result) { const won = pay(bet * 1.92, 'Coinflip'); setStatus('coinStatus', `${result}. You won ${money(won)}.`, 'win'); } else { addLog(`<b>Coinflip:</b> ${result}, lost ${money(bet)}.`); setStatus('coinStatus', `${result}. You lost.`, 'lose'); } busy = false; }

async function baccarat(side) { const bet = getBet('baccaratBet'); const err = chargeBet(bet); if (err) return toast(err); busy = true; const player = [], banker = []; document.querySelectorAll('.baccarat-player,.baccarat-banker').forEach(el => el.classList.remove('side-win')); setStatus('baccaratStatus', 'Cards sliding from the shoe...'); renderCards('baccaratPlayerCards', player); renderCards('baccaratBankerCards', banker); for (let i = 0; i < 2; i++) { player.push(card()); renderCards('baccaratPlayerCards', player, false, true); await sleep(420); banker.push(card()); renderCards('baccaratBankerCards', banker, false, true); await sleep(420); } let ps = handValue(player) % 10, bs = handValue(banker) % 10; if (ps <= 5) { setStatus('baccaratStatus', 'Player draws a third card...'); await sleep(520); player.push(card()); renderCards('baccaratPlayerCards', player, false, true); ps = handValue(player) % 10; } if (bs <= 5) { setStatus('baccaratStatus', 'Banker draws...'); await sleep(520); banker.push(card()); renderCards('baccaratBankerCards', banker, false, true); bs = handValue(banker) % 10; } if ($('baccaratPlayerScore')) $('baccaratPlayerScore').textContent = '(' + ps + ')'; if ($('baccaratBankerScore')) $('baccaratBankerScore').textContent = '(' + bs + ')'; await sleep(650); const winner = ps === bs ? 'Tie' : ps > bs ? 'Player' : 'Banker'; if (winner === 'Player') document.querySelector('.baccarat-player')?.classList.add('side-win'); if (winner === 'Banker') document.querySelector('.baccarat-banker')?.classList.add('side-win'); if (side === winner) { const mult = side === 'Tie' ? 8 : side === 'Banker' ? 1.82 : 1.92; const won = pay(bet * mult, 'Baccarat'); setStatus('baccaratStatus', `${winner} wins. You won ${money(won)}.`, 'win'); } else { addLog(`<b>Baccarat:</b> ${winner} won, lost ${money(bet)}.`); setStatus('baccaratStatus', `${winner} wins. You lost.`, 'lose'); } busy = false; }

function buildPlinko() { const board = $('plinkoBoard'); if (!board) return; board.innerHTML = ''; for (let r = 0; r < 9; r++) { const row = document.createElement('div'); row.className = 'peg-row'; for (let c = 0; c <= r; c++) row.innerHTML += '<span></span>'; board.appendChild(row); } }
function choosePlinkoSlot() { let slot = 4; for (let i = 0; i < 10; i++) { slot += Math.random() < 0.5 ? -1 : 1; slot = clamp(slot, 0, 8); } return slot; }
function plinkoPegMap(board) { const box = board.getBoundingClientRect(); return [...board.querySelectorAll('.peg-row span')].map(peg => { const p = peg.getBoundingClientRect(); return { x: p.left - box.left + p.width / 2, y: p.top - box.top + p.height / 2, hit: false }; }); }
function runPlinkoPhysics(board, ball, targetSlot) { return new Promise(resolve => { const w = board.clientWidth || 760, h = board.clientHeight || 460, radius = 12, slotW = w / 9, targetX = slotW * (targetSlot + 0.5), targetY = h - radius - 4, pegs = plinkoPegMap(board); let x = w / 2, y = 18, vx = (Math.random() - 0.5) * 0.7, vy = 0, last = performance.now(); function draw() { ball.style.transform = `translate3d(${x - radius}px, ${y - radius}px, 0)`; } function tick(now) { const dt = Math.min(32, now - last) / 16.67; last = now; vy += 0.18 * dt; vx *= 0.993; const progress = clamp(y / h, 0, 1); if (progress > 0.58) vx += (targetX - x) * 0.0017 * dt; x += vx * dt; y += vy * dt; if (x < radius) { x = radius; vx = Math.abs(vx) * 0.72; } if (x > w - radius) { x = w - radius; vx = -Math.abs(vx) * 0.72; } for (const peg of pegs) { const dx = x - peg.x, dy = y - peg.y, dist = Math.hypot(dx, dy), min = radius + 7; if (dist > 0 && dist < min && vy > -2.6) { const nx = dx / dist, ny = dy / dist; x = peg.x + nx * min; y = peg.y + ny * min; const dot = vx * nx + vy * ny; vx = (vx - 1.55 * dot * nx) * 0.82 + (Math.random() - 0.5) * 0.44; vy = (vy - 1.55 * dot * ny) * 0.82; peg.hit = true; } } if (y > h * 0.78) { vx += (targetX - x) * 0.0038 * dt; vy = Math.min(vy, 5.2); } if (y >= targetY) { x += (targetX - x) * 0.38; y = targetY; draw(); resolve(); return; } draw(); requestAnimationFrame(tick); } draw(); requestAnimationFrame(tick); }); }
async function dropPlinko() { const bet = getBet('plinkoBet'); const err = chargeBet(bet); if (err) return toast(err); busy = true; const board = $('plinkoBoard'); const ball = document.createElement('div'); ball.className = 'plinko-ball'; board.appendChild(ball); setStatus('plinkoStatus', 'Ball dropped... bouncing through the pegs.'); const mults = [0.2,0.4,0.7,0.9,1.6,0.9,1.2,0.6,0.2]; const slot = choosePlinkoSlot(); await runPlinkoPhysics(board, ball, slot); const won = pay(bet * mults[slot], 'Plinko'); document.querySelectorAll('.plinko-slots span').forEach((s, i) => s.classList.toggle('hit', i === slot)); setStatus('plinkoStatus', `Landed on ${mults[slot]}x. Paid ${money(won)}.`, mults[slot] >= 1.1 ? 'win' : 'lose'); await sleep(850); ball.remove(); busy = false; }

function updateDiceStatus() { if (!$('diceTarget')) return; const target = clamp(Number($('diceTarget').value), 5, 95); $('diceTarget').value = target; const chance = (100 - target) / 100; setStatus('diceStatus', `Win chance: ${(chance * 100).toFixed(1)}% · Payout: ${payoutMultiplier(chance).toFixed(2)}x.`); }
async function rollDice() { const bet = getBet('diceBet'); const err = chargeBet(bet); if (err) return toast(err); busy = true; const result = $('diceResult'); result?.classList.add('rolling'); setStatus('diceStatus', 'Dice rolling...'); for (let i = 0; i < 12; i++) { if (result) result.textContent = (Math.random() * 100).toFixed(2); await sleep(80); } const target = clamp(Number($('diceTarget').value), 5, 95); const roll = Math.floor(Math.random() * 10000) / 100; if (result) { result.textContent = roll.toFixed(2); result.classList.remove('rolling'); } if (roll > target) { const won = pay(bet * payoutMultiplier((100 - target) / 100), 'Dice'); setStatus('diceStatus', `Rolled ${roll.toFixed(2)}. Won ${money(won)}.`, 'win'); } else { addLog(`<b>Dice:</b> rolled ${roll.toFixed(2)} and lost ${money(bet)}.`); setStatus('diceStatus', `Rolled ${roll.toFixed(2)}. Needed over ${target}.`, 'lose'); } busy = false; }

on('depositBtn', 'click', deposit); on('withdrawBtn', 'click', withdraw); on('dailyBonusBtn', 'click', dailyBonus); on('minesStart', 'click', startMines); on('minesCashout', 'click', cashoutMines); on('blackjackDeal', 'click', dealBlackjack); on('blackjackHit', 'click', hitBlackjack); on('blackjackStand', 'click', standBlackjack); on('coinHeads', 'click', () => flipCoin('Heads')); on('coinTails', 'click', () => flipCoin('Tails')); on('betPlayer', 'click', () => baccarat('Player')); on('betBanker', 'click', () => baccarat('Banker')); on('betTie', 'click', () => baccarat('Tie')); on('plinkoDrop', 'click', dropPlinko); on('diceRoll', 'click', rollDice); on('diceTarget', 'input', updateDiceStatus);
document.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => switchTab(btn.dataset.target)));
render(); renderMines(); buildPlinko(); updateDiceStatus(); openHashGame();
